[project]
name = "ot-croissant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mlcroissant>=1.0.12",
    "pip>=25.0.1",
    "polars>=1.21.0",
    "pyarrow>=19.0.0",
    "pyspark>=3.5.4",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "ipython>=8.32.0",
    "ruff>=0.9.3",
]
